{
 "title": "Default traffics",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "service", "query": { "query": "label_values(exported_job)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values(marketpulse_go_goroutine_count{exported_job=~\"^$service$\"}, exported_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Scheduler Latency (goroutine wait time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50,\r\n  rate(marketpulse_go_schedule_duration_seconds_bucket{exported_instance=\"$instance\"}[1m])\r\n)",
     "legendFormat": "median"
    },
    {
     "expr": "histogram_quantile(0.95,\r\n  rate(marketpulse_go_schedule_duration_seconds_bucket{exported_instance=\"$instance\"}[1m])\r\n)",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99,\r\n  rate(marketpulse_go_schedule_duration_seconds_bucket{exported_instance=\"$instance\"}[1m])\r\n)",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Goroutine",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "marketpulse_go_goroutine_count{exported_job=~\"^$service$\", exported_instance=~\"^$instance$\"}",
     "legendFormat": "Goroutines"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(marketpulse_process_cpu_seconds_total{exported_job=~\"^$service$\", exported_instance=~\"^$instance$\"}[2m]))",
     "legendFormat": "CPU Core Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "marketpulse_go_memory_used_bytes{exported_job=~\"^$service$\", exported_instance=~\"^$instance$\"}",
     "legendFormat": "RAM - {{go_memory_type}}"
    }
   ]
  }
 ]
}