{
 "title": "MarketPulse-Aggregator",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(marketpulse_target_info{exported_job=\"marketpulse-aggregator\"},exported_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Tick Processing Throughput (TPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(irate(marketpulse_tick_events_total{exported_instance=~\"^$instance$\"}[2m])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "marketpulse_go_memory_used_bytes{exported_instance=~\"^$instance$\"}",
     "legendFormat": "RAM (Heap Inuse)"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(marketpulse_process_cpu_seconds_total{exported_instance=~\"^$instance$\"}[2m]))",
     "legendFormat": "CPU Core Usage"
    }
   ]
  },
  {
   "title": "Goroutine",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "marketpulse_go_goroutine_count{exported_instance=~\"^$instance$\"}",
     "legendFormat": "Goroutines"
    }
   ]
  }
 ]
}