{
 "title": "MarketPulse-Orderbook",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(marketpulse_target_info{exported_job=~\"marketpulse-orderbook\"},exported_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overall Success Rate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(marketpulse_orderbook_events_by_status_total{status=\"applied\", exported_instance=~\"^$instance$\"}[5m]))\r\n/\r\nsum(rate(marketpulse_orderbook_events_by_status_total{status=~\"applied|dropped_gap\", exported_instance=~\"^$instance$\"}[5m]))\r\n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Symbols by Exchange",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(marketpulse_orderbook_active_symbols{exported_instance=~\"^$instance$\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by (exchange) (\r\n  marketpulse_orderbook_active_symbols{exported_instance=~\"^$instance$\"}\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Rate by Exchange",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (exchange) (\r\n  rate(marketpulse_orderbook_events_by_status_total{status=\"applied\", exported_instance=~\"^$instance$\"}[1m]))\r\n/\r\nsum by (exchange) (\r\n  rate(marketpulse_orderbook_events_by_status_total{status=~\"applied|dropped_gap\", exported_instance=~\"^$instance$\"}[1m])\r\n)\r\n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TPS by Exchange",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (exchange) (irate(marketpulse_orderbook_events_by_status_total{exported_instance=~\"^$instance$\", status=\"applied\"}[1m]))",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Latency by Exchange",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,\r\n  sum by (exchange, le) (\r\n    rate(marketpulse_orderbook_events_latency_ms_bucket{exported_instance=~\"^$instance$\"}[1m])\r\n    )\r\n)",
     "legendFormat": "p50-{{exchange}}"
    },
    { "legendFormat": "__auto" },
    {
     "expr": "histogram_quantile(0.95,\r\n  sum by (exchange, le) (\r\n    rate(marketpulse_orderbook_events_latency_ms_bucket{exported_instance=~\"^$instance$\"}[1m])\r\n    )\r\n)",
     "legendFormat": "p95-{{exchange}}"
    },
    {
     "expr": "histogram_quantile(0.99,\r\n  sum by (exchange, le) (\r\n    rate(marketpulse_orderbook_events_latency_ms_bucket{exported_instance=~\"^$instance$\"}[1m])\r\n    )\r\n)",
     "legendFormat": "p99-{{exchange}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "marketpulse_go_memory_used_bytes{exported_instance=~\"^$instance$\"}",
     "legendFormat": "{{go_memory_type}}"
    }
   ]
  },
  {
   "title": "Goroutine",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "marketpulse_go_goroutine_count{exported_instance=~\"^$instance$\"}",
     "legendFormat": "Goroutines"
    }
   ]
  },
  {
   "title": " Scheduler Latency (goroutine wait time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50,\r\n  rate(marketpulse_go_schedule_duration_seconds_bucket{exported_instance=\"$instance\"}[1m])\r\n)",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95,\r\n  rate(marketpulse_go_schedule_duration_seconds_bucket{exported_instance=\"$instance\"}[1m])\r\n)",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99,\r\n  rate(marketpulse_go_schedule_duration_seconds_bucket{exported_instance=\"$instance\"}[1m])\r\n)",
     "legendFormat": "p99"
    }
   ]
  }
 ]
}