{
 "title": "MarketPulse-Broadcaster",
 "time": { "from": "2026-04-22T13:11:14.643Z", "to": "2026-04-22T13:31:14.643Z" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(marketpulse_target_info{exported_job=\"marketpulse-broadcaster\"},exported_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Client drop total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(marketpulse_broadcaster_client_drops_total{exported_instance=~\"^$instance$\"}[3m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Drop Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(reason) (irate(marketpulse_broadcaster_client_drops_total{exported_instance=~\"^$instance$\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Message Processed (TPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(stream) (irate(marketpulse_broadcaster_messages_total{exported_instance=~\"^$instance$\"}[1m]))",
     "legendFormat": "{{stream}}"
    }
   ]
  },
  {
   "title": "Active Client & Room",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "marketpulse_broadcaster_active_rooms{exported_instance=~\"^$instance$\"}",
     "legendFormat": "Rooms"
    },
    {
     "expr": "marketpulse_broadcaster_active_clients{exported_instance=~\"^$instance$\"}",
     "legendFormat": "Clients"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(marketpulse_broadcaster_broadcast_latency_ms_bucket{exported_instance=~\"^$instance$\"}[1m]))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, rate(marketpulse_broadcaster_broadcast_latency_ms_bucket{exported_instance=~\"^$instance$\"}[1m]))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, rate(marketpulse_broadcaster_broadcast_latency_ms_bucket{exported_instance=~\"^$instance$\"}[1m]))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Goroutine",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "marketpulse_go_goroutine_count{exported_instance=~\"^$instance$\"}",
     "legendFormat": "Goroutines"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "marketpulse_go_memory_used_bytes{exported_instance=~\"^$instance$\"}",
     "legendFormat": "RAM (Heap Inuse)"
    }
   ]
  },
  {
   "title": "CmdChanQueueLength ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "marketpulse_broadcaster_cmdchan_queue_length{exported_instance=~\"^$instance$\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(marketpulse_process_cpu_seconds_total{exported_instance=~\"^$instance$\"}[2m]))",
     "legendFormat": "CPU Core Usage"
    }
   ]
  }
 ]
}